/*
 * This Java source file was generated by the Gradle 'init' task.
 * @author Carles Bernabeu Molió
 */
package CalculadoraJunit;

/**
 * Esta clase representa una calculadora básica que puede realizar operaciones aritméticas simples
 * y mantener un registro del último resultado y la última operación realizada.
 */
public class CalculadoraJunit {
    private float lastResult;
    private String lastOp;

    /**
     * Obtiene el último resultado obtenido por la calculadora.
     *
     * @return el último resultado obtenido
     */
    public float getLastResult() {
        return this.lastResult;
    }

    /**
     * Obtiene la última operación realizada por la calculadora.
     *
     * @return la última operación realizada
     */
    public String getLastOp() {
        return this.lastOp;
    }

    /**
     * Realiza la operación de suma entre dos números.
     *
     * @param op1 el primer operando
     * @param op2 el segundo operando
     * @return el resultado de la suma
     */
    public float suma(float op1, float op2) {
        float result = op1 + op2;
        this.lastResult = result;
        this.lastOp = "Suma";
        return result;
    }

    /**
     * Realiza la operación de resta entre dos números.
     *
     * @param op1 el primer operando
     * @param op2 el segundo operando
     * @return el resultado de la resta
     */
    public float resta(float op1, float op2) {
        float result = op1 - op2;
        this.lastResult = result;
        this.lastOp = "Resta";
        return result;
    }

    /**
     * Realiza la operación de multiplicación entre dos números.
     *
     * @param op1 el primer operando
     * @param op2 el segundo operando
     * @return el resultado de la multiplicación
     */
    public float multiplica(float op1, float op2) {
        float result = op1 * op2;
        this.lastResult = result;
        this.lastOp = "Multiplica";
        return result;
    }

    /**
     * Realiza la operación de división entre dos números.
     *
     * @param op1 el dividendo
     * @param op2 el divisor
     * @return el resultado de la división
     */
    public float divideix(float op1, float op2) {
        float result = op1 / op2;
        this.lastResult = result;
        this.lastOp = "Divideix";
        return result;
    }

    /**
     * Comprueba si el primer número es mayor que el segundo.
     *
     * @param op1 el primer número
     * @param op2 el segundo número
     * @return true si el primer número es mayor que el segundo, false en caso contrario
     */
    public boolean majorQue(float op1, float op2) {
        return op1 > op2;
    }

    /**
     * Restablece el último resultado y la última operación realizada a sus valores predeterminados.
     */
    public void restablecer() {
        this.lastResult = 0;
        this.lastOp = "Ninguna";
    }
}